# Generated by Django 6.0.3 on 2026-06-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_task_owner_task_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('tasks', models.ManyToManyField(related_name='developers', to='projects.task')),
            ],
        ),
    ]
